spring:
  datasource:
        url: jdbc:mysql://127.0.0.1:3306/fastcampus_pay?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: mysqluser
        password: mysqlpw
        driver-class-name: com.mysql.cj.jdbc.Driver

  batch: #TODO
    jdbc:
      initialize-schema: always
    job.name: ${job.name:NONE}
    chunk-size: 1000


  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**