spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          configuration:
            auto.offset.reset: earliest
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

      bindings:
        kafka-test-out-0:
          content-type: text/plain
          destination: domain-event-string
          group: consumer-group-string
